site_name: Pi-NAS Docs
site_url: https://pi-nas-docs.github.io
theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  features:
    - navigation.sections
    - navigation.footer
plugins:
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/pi-nas
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/pi-nas
  generator: false
