site_name: Willz Cloud
site_url: https://willzcloud.github.io
theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  features:
    - navigation.sections
    - navigation.footer
plugins:
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/willzcloud
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/willzcloud
  generator: false
